spring:
  datasource:
    url: jdbc:oracle:thin:@fei-sql3.upceucebny.cz:1521:BDAS
    username: st67059
    password: pepa
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true